version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: myclabs/php-enum
    versions:
    - 1.8.0
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.0
    - 9.5.1
    - 9.5.2
  - dependency-name: guzzlehttp/guzzle
    versions:
    - 7.2.0
